import assert from "node:assert/strict";
import test from "node:test";

import {
    mkdtemp,
    readFile,
    rm
} from "node:fs/promises";

import {
    tmpdir
} from "node:os";

import {
    join
} from "node:path";

import {
    loadRiverDevConfiguration
} from "../core/config";

import {
    createImplementationRunner,
    validateImplementationManifest
} from "./runner";

import type {
    RiverDevImplementationManifest
} from "./runner";


async function createTemporaryGitRepository():
Promise<string> {

    const root =
        await mkdtemp(
            join(
                tmpdir(),
                "river-dev-implementation-"
            )
        );

    const {
        execFile
    } =
        await import(
            "node:child_process"
        );

    const {
        promisify
    } =
        await import(
            "node:util"
        );

    const execute =
        promisify(
            execFile
        );

    await execute(
        "git",
        [
            "init"
        ],
        {
            cwd:
                root
        }
    );

    await execute(
        "git",
        [
            "checkout",
            "-b",
            "dev-02-safe-implementation-engine"
        ],
        {
            cwd:
                root
        }
    );

    return root;

}


function createManifest(
    path:
        string = "generated/example.txt"
): RiverDevImplementationManifest {

    return {

        version:
            "1.0.0",

        implementationId:
            "implementation:test",

        planId:
            "plan:test",

        branch:
            "dev-02-safe-implementation-engine",

        description:
            "Test safe implementation.",

        operations: [
            {
                type:
                    "write-file",

                path,

                content:
                    "Generated by River Dev.\n",

                overwrite:
                    true
            }
        ]

    };

}


test(
    "validates a safe implementation manifest",
    async () => {

        const root =
            await createTemporaryGitRepository();

        try {

            const baseConfiguration =
                await loadRiverDevConfiguration(
                    process.cwd()
                );

            const configuration = {

                ...baseConfiguration,

                repositoryRoot:
                    root,

                policyRoot:
                    join(
                        root,
                        ".river-dev"
                    )

            };

            assert.doesNotThrow(
                () => {
                    validateImplementationManifest(
                        configuration,
                        createManifest()
                    );
                }
            );

        }
        finally {

            await rm(
                root,
                {
                    recursive:
                        true,
                    force:
                        true
                }
            );

        }

    }
);


test(
    "dry run validates without writing files",
    async () => {

        const root =
            await createTemporaryGitRepository();

        try {

            const baseConfiguration =
                await loadRiverDevConfiguration(
                    process.cwd()
                );

            const configuration = {

                ...baseConfiguration,

                repositoryRoot:
                    root,

                policyRoot:
                    join(
                        root,
                        ".river-dev"
                    )

            };

            const runner =
                createImplementationRunner(
                    configuration
                );

            const result =
                await runner.execute(
                    createManifest(),
                    "dry-run"
                );

            assert.equal(
                result.applied,
                false
            );

            assert.equal(
                result.operations[0]?.status,
                "validated"
            );

            await assert.rejects(
                async () => {
                    await readFile(
                        join(
                            root,
                            "generated",
                            "example.txt"
                        ),
                        "utf8"
                    );
                }
            );

        }
        finally {

            await rm(
                root,
                {
                    recursive:
                        true,
                    force:
                        true
                }
            );

        }

    }
);


test(
    "apply mode writes approved repository files",
    async () => {

        const root =
            await createTemporaryGitRepository();

        try {

            const baseConfiguration =
                await loadRiverDevConfiguration(
                    process.cwd()
                );

            const configuration = {

                ...baseConfiguration,

                repositoryRoot:
                    root,

                policyRoot:
                    join(
                        root,
                        ".river-dev"
                    )

            };

            const runner =
                createImplementationRunner(
                    configuration
                );

            const result =
                await runner.execute(
                    createManifest(),
                    "apply"
                );

            const source =
                await readFile(
                    join(
                        root,
                        "generated",
                        "example.txt"
                    ),
                    "utf8"
                );

            assert.equal(
                result.applied,
                true
            );

            assert.equal(
                source,
                "Generated by River Dev.\n"
            );

        }
        finally {

            await rm(
                root,
                {
                    recursive:
                        true,
                    force:
                        true
                }
            );

        }

    }
);


test(
    "rejects protected paths",
    async () => {

        const root =
            await createTemporaryGitRepository();

        try {

            const baseConfiguration =
                await loadRiverDevConfiguration(
                    process.cwd()
                );

            const configuration = {

                ...baseConfiguration,

                repositoryRoot:
                    root,

                policyRoot:
                    join(
                        root,
                        ".river-dev"
                    )

            };

            assert.throws(
                () => {
                    validateImplementationManifest(
                        configuration,
                        createManifest(
                            ".env"
                        )
                    );
                },
                TypeError
            );

        }
        finally {

            await rm(
                root,
                {
                    recursive:
                        true,
                    force:
                        true
                }
            );

        }

    }
);


test(
    "rejects paths outside the repository",
    async () => {

        const root =
            await createTemporaryGitRepository();

        try {

            const baseConfiguration =
                await loadRiverDevConfiguration(
                    process.cwd()
                );

            const configuration = {

                ...baseConfiguration,

                repositoryRoot:
                    root,

                policyRoot:
                    join(
                        root,
                        ".river-dev"
                    )

            };

            assert.throws(
                () => {
                    validateImplementationManifest(
                        configuration,
                        createManifest(
                            "../outside.txt"
                        )
                    );
                },
                TypeError
            );

        }
        finally {

            await rm(
                root,
                {
                    recursive:
                        true,
                    force:
                        true
                }
            );

        }

    }
);


test(
    "rejects duplicate operation paths",
    async () => {

        const root =
            await createTemporaryGitRepository();

        try {

            const baseConfiguration =
                await loadRiverDevConfiguration(
                    process.cwd()
                );

            const configuration = {

                ...baseConfiguration,

                repositoryRoot:
                    root,

                policyRoot:
                    join(
                        root,
                        ".river-dev"
                    )

            };

            const manifest = {

                ...createManifest(),

                operations: [
                    ...createManifest().operations,
                    ...createManifest().operations
                ]

            };

            assert.throws(
                () => {
                    validateImplementationManifest(
                        configuration,
                        manifest
                    );
                },
                TypeError
            );

        }
        finally {

            await rm(
                root,
                {
                    recursive:
                        true,
                    force:
                        true
                }
            );

        }

    }
);
